dist: xenial
language: node_js
cache: yarn
services:
  - docker
env:
  global:
    - MONGO_INITDB_DATABASE=get_fit
    - MONGO_PROD_DBNAME=get_fit
    - MONGO_LOCAL_PORT=27017
    - MONGO_LOCAL_SERVICENAME=mongo

# Make the install command build the containers
install: yarn build:test

# run tests!
# script: 'yarn up:test'
script: ''

# bring down the test containers we used
# after_script: yarn down:test
after_script: ''

# deploy!
deploy:
  # deploy tags
  - provider: script
    script: bash deploy/docker-push.sh
    # prevent travis from resetting the working dir so we can deploy
    skip_cleanup: true
    on:
      all_branches: true
  # deploy releases
  - provider: releases
    api_key: $GITHUB_PAT
    # prevent travis from resetting the working dir so we can deploy
    skip_cleanup: true
    on:
      branch: master
      tags: true
