dist: xenial
language: node_js
cache: yarn
services:
  - docker

# Make the install command build the containers
install: bash ci/build.sh

# run tests!
script: yarn up:test

# bring down the test containers we used
after_script: yarn down:test
