dist: xenial
language: node_js
cache: yarn
services:
  - docker
env:
  global:
    - MONGO_INITDB_DATABASE=get_fit
    - MONGO_PROD_DBNAME=get_fit
    - MONGO_LOCAL_PORT=27017
    - MONGO_LOCAL_SERVICENAME=mongo

# Build Images before we start
before_script:
  - yarn build:test

# Do nothing as the install command, since we are using Docker
install:
  - snyk protect
  - snyk test

# When to run certain stages
stages:
  - name: tests
    # Don't run!
    if: false IS true
  - name: cleanup_tests
    # Don't run!
    if: false IS true
  - deploy

# Run our tests
jobs:
  include:
    # Run our tests
    - stage: 'tests'
      name: 'Unit Tests'
      script: yarn up:test
    # Clean up after our tests
    - stage: 'cleanup_tests'
      name: 'Clean Up Tests'
      script: yarn down:test

after_success:
  - snyk monitor

# skip_cleanup prevents travis from resetting the working directory so we can
# deploy properly
deploy:
  # deploy tags
  - provider: script
    script: bash scripts/deploy.sh
    skip_cleanup: true
    on:
      all_branches: true

after_deploy:
  - snyk monitor
