dist: xenial
language: node_js
cache: yarn
services:
  - docker
env:
  global:
    - MONGO_INITDB_DATABASE=get_fit
    - MONGO_PROD_DBNAME=get_fit
    - MONGO_LOCAL_PORT=27017
    - MONGO_LOCAL_SERVICENAME=mongo

# Make the install command build the containers
install: bash ci/build.sh

before_script: yarn up:test

# run tests!
script: docker exec get_fit_jasmine yarn test:all

# bring down the test containers we used
after_script: yarn down:test
