dist: xenial
language: node_js
cache: npm
services:
  - docker

# Make the install command build the containers
install: bash ci/build.sh

# run tests!
script: npm run up:test

# bring down the test containers we used
after_script: npm run down:test

# deploy!
deploy:
  # deploy tags
  - provider: script
    script: bash ci/docker-push.sh
    # prevent travis from resetting the working dir so we can deploy
    skip_cleanup: true
    # Run on all branches and let our script handle the conditionals
    on:
      all_branches: true

notifications:
  webhooks:
    urls:
      - https://samhinshaw.com/hooks/travis
    on_success: always # default: always
    on_failure: never # default: always
    on_start: never # default: never
    on_cancel: never # default: always
    on_error: never # default: always
