dist: xenial
language: node_js
cache: yarn
services:
  - docker
env:
  global:
    - MONGO_INITDB_DATABASE=get_fit
    - MONGO_PROD_DBNAME=get_fit
    - MONGO_LOCAL_PORT=27017
    - MONGO_LOCAL_SERVICENAME=mongo

# Make the install command build the containers
install: yarn build:test

script: yarn up:test

after_script: yarn down:test

# skip_cleanup prevents travis from resetting the working directory so we can
# deploy properly
deploy:
  # deploy tags
  - provider: script
    script: bash scripts/deploy.sh
    skip_cleanup: true
    on:
      all_branches: true
  # deploy releases
  - provider: releases
    api_key: $GITHUB_PAT
    skip_cleanup: true
    on:
      branch: master
      tags: true
