dist: xenial
language: node_js
cache: yarn
services:
  - docker
env:
  global:
    - MONGO_INITDB_DATABASE=get_fit
    - MONGO_PROD_DBNAME=get_fit
    - MONGO_LOCAL_PORT=27017
    - MONGO_LOCAL_SERVICENAME=mongo
jobs:
  include:
    - stage: 'Build'
      install: skip
      script: yarn build:test
    - stage: 'Test'
      name: 'Unit Tests'
      install: skip
      script: yarn up:test
