dist: xenial
language: node_js
cache: yarn
services:
  - docker
env:
  global:
    - MONGO_INITDB_DATABASE=get_fit
    - MONGO_PROD_DBNAME=get_fit
    - MONGO_LOCAL_PORT=27017
    - MONGO_LOCAL_SERVICENAME=mongo

# Build Images before we start
before_script: yarn build:test

# Do nothing as the install command, since we are using Docker
install: ''

# When to run certain stages
stages:
  - name: build_tests
  - name: tests
    # Don't run!
    if: false IS true
  - name: cleanup_tests
    # Don't run!
    if: false IS true
  - deploy

# Run our tests
jobs:
  include:
    # Run our tests
    - stage: 'tests'
      name: 'Unit Tests'
      script: yarn up:test
    # Clean up after our tests
    - stage: 'cleanup_tests'
      name: 'Clean Up Tests'
      script: yarn down:test

deploy:
  provider: script
  script: bash deploy/docker-push.sh
  on:
    condition: $TRAVIS_BRANCH =~ ^release || -v $TRAVIS_TAG
