version: '3' # this specifies the docker-compose version

services:
  # Start backend Express.js server
  node:
    build: .
    # Set the NODE_ENV to the dev environment
    environment:
      - NODE_ENV=production
    command: ['yarn', 'run:prod']
    ports:
      - '8005:8005'
