version: '3.4'

services:
  # Start backend Express.js server
  node:
    image: samhinshaw/get_fit:${DOCKER_TAG:-latest}
    # Set the NODE_ENV to the dev environment
    environment:
      - NODE_ENV=production
    restart: always
    ports:
      - '8005:8005'
    env_file:
      - .env
